server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3307/tutorflow_auth
    username: tutorflow
    password: tutorflow123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


jwt:
  secret: tutorflow-super-secret-key-change-this-in-production
  expiration: 86400000